/**
 * NPC VIETNAM - GLOBAL CLASSIC VIETNAM
 * Bilingual Translation Dictionary (Tiếng Việt & English)
 * Standard IFBB Pro League & NPC Worldwide Bodybuilding Terminology
 */

const i18nData = {
  vi: {
    // Header & Navigation
    nav_home: "Trang chủ",
    nav_about: "Giới thiệu",
    nav_procard: "Pro Cards",
    nav_divisions: "Hạng mục",
    nav_schedule: "Lịch trình",
    nav_packages: "Gói đấu",
    nav_judges: "Giám khảo",
    nav_gallery: "Thư viện",
    nav_faq: "FAQ",
    btn_register_nav: "Đăng ký thi đấu",

    // Hero Section
    hero_badge: "NPC REGIONAL & IFBB PRO QUALIFIER",
    hero_title_sub: "CONQUER THE STAGE",
    hero_desc: "Đấu trường thể hình đỉnh cao thuộc hệ thống NPC Worldwide & IFBB Pro League. Nơi hội tụ các chiến binh xuất sắc nhất tranh đoạt 8 chiếc thẻ IFBB PRO CARD vươn tầm thế giới.",
    btn_hero_register: "Đăng ký thi đấu ngay",
    btn_hero_trailer: "Trailer 4K Sân Khấu",
    stat_pro_cards: "IFBB PRO CARDS",
    stat_athletes: "Vận động viên",
    stat_stadium: "HCMC Stadium",
    scroll_down: "CUỘN XUỐNG",

    // Pro Cards Section
    procard_eyebrow: "ĐỈNH CAO DANH VỌNG",
    procard_title: "TRANH ĐOẠT 08 CHIẾC THẺ IFBB PRO CARD",
    procard_subtitle: "Chiếc vé thông hành quyền lực nhất thế giới thể hình, mở toang cánh cửa bước ra đấu trường Olympia danh giá tại Hoa Kỳ",
    procard_alloc_title: "Phân Bổ 8 Thẻ IFBB Pro Card Năm 2026",
    procard_alloc_desc: "Mỗi hạng mục thi đấu sẽ tìm ra các nhà vô địch Overall để trao trực tiếp thẻ Pro Card ngay trong đêm Gala Chung Kết:",
    procard_mens_physique: "02 Thẻ Pro Card (Open & Masters)",
    procard_classic: "02 Thẻ Pro Card (Open Division)",
    procard_bodybuilding: "01 Thẻ Pro Card (Overall Champion)",
    procard_bikini: "01 Thẻ Pro Card (Overall Champion)",
    procard_wellness: "01 Thẻ Pro Card (Overall Champion)",
    procard_figure: "01 Thẻ Pro Card (Overall Champion)",
    road_step1_title: "Gia Nhập NPC Worldwide",
    road_step1_desc: "Thi đấu giải Regional trong nước để tích lũy điểm & kinh nghiệm sân khấu.",
    road_step2_title: "Giành Overall Tại Global Classic",
    road_step2_desc: "Vượt qua các đối thủ sừng sỏ nhất để nhận thẻ IFBB Pro Card chính thức.",
    road_step3_title: "Bản Đồ IFBB Pro Thế Giới",
    road_step3_desc: "Tham gia các giải Pro Show toàn cầu tranh vé bước vào thánh đường Mr. Olympia.",

    // About Section
    about_eyebrow: "DI SẢN & TIÊU CHUẨN",
    about_title: "ĐẲNG CẤP THỂ HÌNH CHUYÊN NGHIỆP",
    about_natural_title: "Natural Division",
    about_natural_sub: "Chứng nhận thi đấu minh bạch & chuẩn mực",
    about_lead: "Bước ngoặt lịch sử của phong trào thể hình đỉnh cao tại Việt Nam",
    about_p1: "NPC (National Physique Committee) là tổ chức thể hình phong trào lớn nhất hành tinh, chiếc nôi sản sinh ra các huyền thoại Mr. Olympia và vận động viên chuyên nghiệp hàng đầu.",
    about_p2: "Tại Việt Nam, Global Classic Vietnam Championship được vận hành với chuẩn mực quốc tế khắt khe nhất: hệ thống âm thanh, ánh sáng chuyên biệt cho cơ bắp, hội đồng trọng tài quốc tế IFBB uy tín và khâu tổ chức đạt chứng chỉ toàn cầu.",
    feat_pro_title: "Lộ trình IFBB Pro Card",
    feat_pro_desc: "Cửa ngõ chính thức để vận động viên Việt Nam ghi danh tranh vé Pro Qualifier quốc tế.",
    feat_stage_title: "Sân khấu ánh sáng chuyên biệt",
    feat_stage_desc: "Setup ánh sáng mô phỏng 100% sân khấu Arnold Classic & Olympia nhằm tôn vinh từng thớ cơ.",
    stat_lbl_athletes: "Vận động viên tranh tài",
    stat_lbl_divisions: "Thi đấu chuyên nghiệp",
    stat_lbl_fans: "Khán giả & Người hâm mộ",
    stat_lbl_prizes: "Tổng giải thưởng & Quà tặng",

    // Divisions
    div_eyebrow: "DANH MỤC THI ĐẤU",
    div_title: "HẠNG MỤC TRANH TÀI",
    div_subtitle: "Mỗi hạng mục mang một quy chuẩn thẩm mỹ, độ cắt nét và tỷ lệ hình thể riêng biệt",
    div_mp_tag: "Nam Vận Động Viên",
    div_mp_desc: "Tôn vinh hình thể hình chữ V (V-Taper), vai rộng, eo thon gọn, cơ bụng 6 múi sắc nét cùng phong thái tự tin và năng động.",
    div_cp_tag: "Kỷ Nguyên Vàng",
    div_cp_desc: "Sự hồi sinh của vẻ đẹp thể hình cổ điển thời kỳ Arnold Schwarzenegger: cơ bắp dày khối, độ đối xứng hoàn mỹ và Vacuum Pose.",
    div_bb_tag: "Đỉnh Cao Khối Lượng",
    div_bb_desc: "Hạng mục đỉnh cao nhất về độ dày khối cơ (mass), độ xé sợi (conditioning) và chi tiết cơ bắp vượt trội từ đầu đến chân.",
    div_bi_tag: "Nữ Vận Động Viên",
    div_bi_desc: "Tôn vinh đường cong đồng hồ cát nữ tính, cơ mông tròn đầy, độ săn chắc vừa vặn và phong cách trình diễn catwalk quyến rũ.",
    div_wn_tag: "Sức Mạnh & Đường Cong",
    div_wn_desc: "Dành cho các nữ vận động viên có phần thân dưới (đùi, hông, mông) phát triển mạnh mẽ vượt trội nhưng phần thân trên vẫn giữ nét thon gọn.",
    div_fg_tag: "Hình Khối Sắc Nét",
    div_fg_desc: "Tập trung vào độ đối xứng, độ nét của cơ lưng xô hình chữ V, vai tròn và độ tách sợi cơ bắp không quá đồ sộ như Physique.",
    btn_register_div: "Đăng ký hạng này →",

    // Schedule & Countdown
    sched_eyebrow: "ĐẾM NGƯỢC THỜI GIAN",
    sched_title: "LỊCH TRÌNH GIẢI ĐẤU",
    sched_subtitle: "Chuẩn bị sẵn sàng cho ngày hội lớn nhất của thể hình Việt Nam",
    cd_status: "ĐẾM NGƯỢC THỜI GIAN KHỞI TRANH",
    cd_date_info: "3 - 4 THÁNG 10, 2026 • RACH MIEU STADIUM, TP. HỒ CHÍ MINH",
    cd_days: "NGÀY",
    cd_hours: "GIỜ",
    cd_minutes: "PHÚT",
    cd_seconds: "GIÂY",
    banner_caption_title: "Sơ đồ & Quy trình tổ chức tiêu chuẩn",
    banner_caption_desc: "Mọi khung giờ đều được giám sát và vận hành bởi đội ngũ điều phối chuyên nghiệp.",
    step1_title: "Athlete Check-in, Đo Cân & Tanning",
    step1_desc: "Vận động viên nhận số báo danh, kiểm tra chiều cao cân nặng chính thức và hoàn thiện lớp sơn Pro Tan chuẩn sân khấu.",
    step2_title: "Vòng Sơ Loại (Pre-Judging)",
    step2_desc: "Ban giám khảo chấm điểm các vòng Posing so sánh (Quarter Turns & Mandatory Poses) cho tất cả bảng đấu.",
    step3_title: "Chung Kết & Trao Giải (Finals Gala)",
    step3_desc: "Màn trình diễn cá nhân Posing Routine, vinh danh Top 5 các hạng mục và tranh tài Overall Champion.",
    step4_title: "Giao Lưu Khán Giả & Bế Mạc",
    step4_desc: "Chụp ảnh cùng các VĐV vô địch, họp báo cùng báo chí và ban tổ chức NPC Worldwide.",

    // Packages & Services
    pkg_eyebrow: "QUYỀN LỢI & DỊCH VỤ CHUYÊN NGHIỆP",
    pkg_title: "GÓI THI ĐẤU & DỊCH VỤ HỖ TRỢ",
    pkg_subtitle: "Được thiết kế trọn gói từ A-Z giúp vận động viên tập trung 100% tinh thần để đạt phong độ đỉnh cao nhất",
    pkg1_badge: "TIẾT KIỆM 25%",
    pkg1_name: "EARLY ATHLETE",
    pkg1_desc: "Dành cho các VĐV đăng ký sớm trước ngày 15/08/2026.",
    pkg2_badge: "FULL SERVICE",
    pkg2_name: "PRO ATHLETE ALL-IN",
    pkg2_desc: "Giải pháp tối ưu toàn diện từ làn da, hình ảnh đến thẻ Coach hậu trường.",
    pkg3_badge: "ĐA HẠNG MỤC",
    pkg3_name: "CROSSOVER PASS",
    pkg3_desc: "Dành cho VĐV muốn thi đấu thêm bảng thứ 2 (Novice, Masters hoặc Open).",
    btn_pkg_select: "Đăng ký gói này",
    btn_pkg_allin: "Đăng ký trọn gói",
    btn_pkg_cross: "Chọn hạng phụ",
    service_tanning_title: "Dịch Vụ Phun Da Pro Tan",
    service_tanning_desc: "Thực hiện bởi chuyên gia chứng nhận quốc tế, giữ màu chuẩn sáng đèn sân khấu.",
    service_media_title: "Media & Video Posing 4K",
    service_media_desc: "Ống kính chuyên nghiệp ghi lại từng sợi cơ sắc nét và góc quay cinematic.",
    service_coach_title: "Thẻ Coach Hậu Trường",
    service_coach_desc: "Cho phép HLV đồng hành trong khu vực khởi động, bơm cơ và chuẩn bị dầu bóng.",

    // Judges
    judges_eyebrow: "CÔNG TÂM - MINH BẠCH - ĐẲNG CẤP",
    judges_title: "HỘI ĐỒNG GIÁM KHẢO QUỐC TẾ",
    judges_subtitle: "Đội ngũ trọng tài IFBB Pro League kỳ cựu với bề dày hàng thập kỷ chấm điểm tại các đấu trường danh giá bậc nhất thế giới",

    // Drug Test
    dt_badge: "BẢO ĐẢM TÍNH CÔNG BẰNG TUYỆT ĐỐI",
    dt_title: "Quy Chuẩn Kiểm Tra Doping Khắt Khe",
    dt_desc: "Hạng mục Natural Division tại Global Classic Vietnam áp dụng quy trình kiểm tra chất cấm theo tiêu chuẩn của WADA (World Anti-Doping Agency) và NPC Worldwide:",
    dt_poly_title: "Kiểm tra Polygraph (Máy nói dối)",
    dt_poly_desc: "Bắt buộc đối với toàn bộ thí sinh lọt vào Top tranh huy chương Natural.",
    dt_urine_title: "Xét nghiệm mẫu sinh học (Urinalysis Lab Test)",
    dt_urine_desc: "Phân tích mẫu nước tiểu độc lập tại phòng thí nghiệm đạt chuẩn ISO quốc tế.",
    dt_ban_title: "Thời gian cấm kỵ 36 tháng",
    dt_ban_desc: "VĐV không sử dụng bất kỳ chất kích thích đồng hóa (Anabolic Steroids), Hormones tăng trưởng trong 3 năm.",

    // FAQ
    faq_eyebrow: "GIẢI ĐÁP THẮC MẮC",
    faq_title: "CÂU HỎI THƯỜNG GẶP (FAQ)",
    faq_subtitle: "Tất cả những thông tin then chốt vận động viên cần nắm rõ trước ngày bước lên sàn đấu",
    faq_q1: "1. Tôi là vận động viên mới, tôi có thể tham gia Global Classic Vietnam không?",
    faq_a1: "Hoàn toàn được! Giải đấu có các bảng đấu dành cho người mới (True Novice & Novice) trước khi bước vào bảng Open. Đây là cơ hội tuyệt vời nhất để bạn cọ xát và tích lũy bản lĩnh sân khấu tiêu chuẩn quốc tế.",
    faq_q2: "2. Thẻ IFBB Pro Card có giá trị như thế nào?",
    faq_a2: "Thẻ IFBB Pro Card là chứng nhận đẳng cấp cao nhất dành cho VĐV thể hình chuyên nghiệp trên toàn thế giới. Khi sở hữu thẻ Pro Card, bạn chính thức rời khỏi phong trào nghiệp dư để tham gia các giải Pro League thế giới và săn vé đến Mr. Olympia.",
    faq_q3: "3. Quy định về màu da sơn (Tanning) và trang phục thi đấu?",
    faq_a3: "Chỉ chấp nhận các dòng màu da chuyên dụng không lem không dính được IFBB phê duyệt (ưu tiên dịch vụ Official Pro Tan của BTC). Quần Men's Physique phải là Board Shorts dài trên gối; Classic Physique mặc quần đùi đen Classic Trunks; Bikini mặc trang phục 2 mảnh tiêu chuẩn.",
    faq_q4: "4. Tôi cần gửi nhạc trình diễn Posing Routine bằng cách nào?",
    faq_a4: "Đối với hạng mục Bodybuilding & Classic Physique (bài diễn 60 giây), sau khi hoàn tất đăng ký, bạn sẽ nhận được liên kết tải nhạc cá nhân lên hệ thống (định dạng MP3 chất lượng cao). Hạn chót nộp nhạc là 10 ngày trước giải đấu.",
    faq_q5: "5. Khán giả và người thân có thể mua vé vào xem như thế nào?",
    faq_a5: "Vé khán giả (Standard, VIP và VVIP Front-Row) được mở bán trực tiếp tại website này hoặc hotline BTC 093 883 39 79. Mỗi VĐV đăng ký gói Pro VIP đã được tặng kèm 01 vé VIP hàng đầu.",

    // Highlights (Why choose)
    hl_eyebrow: "TẠI SAO CHỌN NPC VIETNAM?",
    hl_title: "GIẢI ĐẤU ĐẲNG CẤP HÀNG ĐẦU",
    hl_subtitle: "Cam kết kiến tạo nền tảng vững chắc nhất cho sự nghiệp thể hình của bạn",
    hl_card1_title: "Chuẩn Quốc Tế NPC",
    hl_card1_desc: "Giải đấu được ủy quyền chính thức, liên kết trực tiếp với hệ sinh thái NPC Worldwide và IFBB Professional League toàn cầu.",
    hl_card2_title: "Ban Giám Khảo Uy Tín",
    hl_card2_desc: "Đội ngũ giám khảo quốc tế có chứng chỉ chấm thi chuyên nghiệp, đảm bảo sự công tâm, minh bạch và chính xác trong từng kết quả.",
    hl_card3_title: "Truyền Thông Bùng Nổ",
    hl_card3_desc: "Đội ngũ nhiếp ảnh và quay phim sân khấu thể thao hàng đầu ghi lại từng khoảnh khắc đỉnh cao, hỗ trợ xây dựng thương hiệu cá nhân VĐV.",
    hl_card4_title: "Cộng Đồng Đẳng Cấp",
    hl_card4_desc: "Môi trường kết nối giữa hàng trăm huấn luyện viên, chủ phòng gym, nhà tài trợ thực phẩm bổ sung và những người đam mê thể hình chân chính.",

    // Sponsors
    sponsors_eyebrow: "ĐỐI TÁC CHIẾN LƯỢC",
    sponsors_title: "ĐỒNG HÀNH CÙNG ĐỈNH CAO THỂ HÌNH VIỆT NAM",

    // Gallery
    gallery_eyebrow: "KHOẢNH KHẮC BẤT TỬ",
    gallery_title: "THƯ VIỆN HÌNH ẢNH",
    gallery_subtitle: "Ánh đèn sân khấu, những thớ cơ cắt xẻ và cảm xúc thăng hoa của nhà vô địch",

    // Register Form
    cta_eyebrow: "CHINH PHỤC ĐỈNH CAO VINH QUANG",
    cta_title: "SẴN SÀNG BƯỚC LÊN SÂN KHẤU?",
    cta_desc: "Đừng để những giọt mồ hôi trong phòng tập nằm lại trong bóng tối. Hãy bước ra ánh sáng, khẳng định sự vượt trội của bản thân trước hàng ngàn khán giả và ghi danh vào lịch sử NPC Vietnam.",
    form_fullname: "Họ và tên *",
    form_fullname_ph: "Ví dụ: Nguyễn Văn A",
    form_phone: "Số điện thoại *",
    form_phone_ph: "Ví dụ: 0912 345 678",
    form_email: "Địa chỉ Email *",
    form_email_ph: "example@domain.com",
    form_division: "Hạng mục đăng ký *",
    form_div_default: "-- Chọn hạng mục thi đấu --",
    form_agree: "Tôi đồng ý với các điều lệ, quy chuẩn kiểm tra doping và cam kết kỷ luật của NPC Worldwide.",
    btn_submit_form: "GỬI ĐĂNG KÝ THI ĐẤU",
    assure_secure: "Bảo mật thông tin VĐV",
    assure_support: "Hỗ trợ kỹ thuật 24/7",
    assure_confirm: "Xác nhận qua email & SMS ngay",

    // Footer
    footer_bio: "Sân chơi thể hình quy mô và chuẩn mực hàng đầu tại Việt Nam, trực thuộc hệ thống thi đấu quốc tế NPC Worldwide và IFBB Pro League.",
    footer_quick_links: "Liên Kết Nhanh",
    footer_rules_support: "Quy Chuẩn & Hỗ Trợ",
    footer_office: "Văn Phòng Ban Tổ Chức",
    footer_address: "Nhà thi đấu Rạch Miễu, 01 Hoa Phượng, Phường 2, Q. Phú Nhuận, TP. Hồ Chí Minh",
    footer_hotline: "Hotline VĐV: 093 883 39 79",
    footer_copyright: "© 2026 NPC Vietnam Championship. Bảo lưu mọi quyền. Liên kết chính thức cùng NPC Worldwide & IFBB Pro League."
  },

  en: {
    // Header & Navigation
    nav_home: "Home",
    nav_about: "About",
    nav_procard: "Pro Cards",
    nav_divisions: "Divisions",
    nav_schedule: "Schedule",
    nav_packages: "Packages",
    nav_judges: "Judges",
    nav_gallery: "Gallery",
    nav_faq: "FAQ",
    btn_register_nav: "Register Now",

    // Hero Section
    hero_badge: "NPC REGIONAL & IFBB PRO QUALIFIER",
    hero_title_sub: "CONQUER THE STAGE",
    hero_desc: "The pinnacle bodybuilding championship sanctioned by NPC Worldwide & IFBB Pro League. Where elite warriors assemble to contest for 8 coveted IFBB PRO CARDS to reach the global stage.",
    btn_hero_register: "Register to Compete",
    btn_hero_trailer: "Official 4K Trailer",
    stat_pro_cards: "IFBB PRO CARDS",
    stat_athletes: "Athletes",
    stat_stadium: "HCMC Stadium",
    scroll_down: "SCROLL DOWN",

    // Pro Cards Section
    procard_eyebrow: "PINNACLE OF GLORY",
    procard_title: "CONTEST FOR 08 IFBB PRO CARDS",
    procard_subtitle: "The most prestigious passport in the bodybuilding world, unlocking the gateway to the legendary Mr. Olympia stage in the USA",
    procard_alloc_title: "8 IFBB Pro Cards Allocation for 2026",
    procard_alloc_desc: "Each competitive division will determine Overall Champions awarded official Pro Cards directly on Finals Gala Night:",
    procard_mens_physique: "02 Pro Cards (Open & Masters)",
    procard_classic: "02 Pro Cards (Open Division)",
    procard_bodybuilding: "01 Pro Card (Overall Champion)",
    procard_bikini: "01 Pro Card (Overall Champion)",
    procard_wellness: "01 Pro Card (Overall Champion)",
    procard_figure: "01 Pro Card (Overall Champion)",
    road_step1_title: "Join NPC Worldwide",
    road_step1_desc: "Compete in domestic Regional contests to accumulate points & stage experience.",
    road_step2_title: "Win Overall at Global Classic",
    road_step2_desc: "Outshine the best competitors to claim your official IFBB Pro Card.",
    road_step3_title: "The Global IFBB Pro Circuit",
    road_step3_desc: "Compete in worldwide Pro Shows to earn qualification directly to Mr. Olympia.",

    // About Section
    about_eyebrow: "LEGACY & STANDARDS",
    about_title: "PREMIER PROFESSIONAL BODYBUILDING",
    about_natural_title: "Natural Division",
    about_natural_sub: "Certified transparent & drug-tested standards",
    about_lead: "A historic milestone for elite bodybuilding in Vietnam",
    about_p1: "The NPC (National Physique Committee) is the largest amateur physique organization on earth, the birthplace of Mr. Olympia legends and world-renowned professional athletes.",
    about_p2: "In Vietnam, the Global Classic Vietnam Championship is executed under rigorous international standards: custom stage lighting tailored for muscle definition, accredited IFBB international judges, and world-class event production.",
    feat_pro_title: "Direct IFBB Pro Pathway",
    feat_pro_desc: "Official gateway for Vietnamese and international athletes to qualify for world Pro Qualifiers.",
    feat_stage_title: "Custom Pro Stage Lighting",
    feat_stage_desc: "100% replicated Arnold Classic & Olympia lighting rigs engineered to accentuate every muscle fiber.",
    stat_lbl_athletes: "Competing Athletes",
    stat_lbl_divisions: "Professional Divisions",
    stat_lbl_fans: "Spectators & Fans",
    stat_lbl_prizes: "Total Awards & Prize Pool",

    // Divisions
    div_eyebrow: "COMPETITION CATEGORIES",
    div_title: "OFFICIAL DIVISIONS",
    div_subtitle: "Each division represents a distinct aesthetic standard, conditioning depth, and physique proportion",
    div_mp_tag: "Men's Category",
    div_mp_desc: "Emphasizes the signature V-Taper, wide shoulders, tapered waist, sculpted six-pack abs, and an energetic, confident stage persona.",
    div_cp_tag: "Golden Era",
    div_cp_desc: "The resurrection of classic bodybuilding aesthetics from the Arnold Schwarzenegger era: dense muscle bellies, flawless symmetry, and the iconic Vacuum Pose.",
    div_bb_tag: "Maximum Mass",
    div_bb_desc: "The pinnacle of muscle density, deep striations, exceptional conditioning, and head-to-toe muscular detail.",
    div_bi_tag: "Women's Category",
    div_bi_desc: "Showcases feminine hourglass curves, full glutes, moderate tone, and an elegant, glamorous runway presentation.",
    div_wn_tag: "Power & Curves",
    div_wn_desc: "Dedicated to female athletes with heavily developed lower bodies (quads, glutes, hamstrings) while maintaining a balanced upper physique.",
    div_fg_tag: "Athletic Symmetry",
    div_fg_desc: "Focuses on muscular symmetry, V-shaped wide lats, rounded delts, and clear separation without extreme mass.",
    btn_register_div: "Register this division →",

    // Schedule & Countdown
    sched_eyebrow: "COUNTDOWN TO SHOWTIME",
    sched_title: "EVENT SCHEDULE",
    sched_subtitle: "Gear up for Vietnam's biggest fitness & bodybuilding festival",
    cd_status: "COUNTDOWN TO SHOWTIME",
    cd_date_info: "OCTOBER 3 - 4, 2026 • RACH MIEU STADIUM, HO CHI MINH CITY",
    cd_days: "DAYS",
    cd_hours: "HOURS",
    cd_minutes: "MINS",
    cd_seconds: "SECS",
    banner_caption_title: "Standard Timeline & Operations",
    banner_caption_desc: "Every minute is supervised and orchestrated by our professional international event team.",
    step1_title: "Athlete Check-in, Weigh-in & Tanning",
    step1_desc: "Competitors receive athlete badges, complete official height/weight verification, and receive base coats of Pro Tan.",
    step2_title: "Pre-Judging Rounds",
    step2_desc: "Judging panel scores comparative posing rounds (Quarter Turns & Mandatory Poses) for all divisions.",
    step3_title: "Finals & Awards Gala",
    step3_desc: "Individual 60-second posing routines, Top 5 medal ceremonies, and the battle for Overall Champion Pro Cards.",
    step4_title: "Fan Meet & Official Closing",
    step4_desc: "Photo sessions with newly crowned champions, official press conference with NPC Worldwide representatives.",

    // Packages & Services
    pkg_eyebrow: "ATHLETE PRIVILEGES & SERVICES",
    pkg_title: "COMPETITION PACKAGES & SUPPORT",
    pkg_subtitle: "End-to-end services crafted so athletes can focus 100% on peak physical and mental condition",
    pkg1_badge: "SAVE 25%",
    pkg1_name: "EARLY ATHLETE",
    pkg1_desc: "Special early-bird rate for athletes registering before August 15, 2026.",
    pkg2_badge: "FULL SERVICE",
    pkg2_name: "PRO ATHLETE ALL-IN",
    pkg2_desc: "All-inclusive VIP package covering professional tanning, media coverage, and backstage pass.",
    pkg3_badge: "MULTI-DIVISION",
    pkg3_name: "CROSSOVER PASS",
    pkg3_desc: "For athletes wishing to enter a second division (True Novice, Masters, or Open).",
    btn_pkg_select: "Select This Package",
    btn_pkg_allin: "Get All-In VIP Package",
    btn_pkg_cross: "Add Crossover Division",
    service_tanning_title: "Official Pro Tan Service",
    service_tanning_desc: "Applied by certified international tanning technicians, calibrated for optimal stage lighting.",
    service_media_title: "Media & 4K Posing Video",
    service_media_desc: "High-end sports photography & cinematic 4K video capturing every muscle striation.",
    service_coach_title: "Backstage Coach Pass",
    service_coach_desc: "Permits personal coaches access to pump-up rooms, glaze applications, and backstage staging.",

    // Judges
    judges_eyebrow: "IMPARTIAL - TRANSPARENT - ELITE",
    judges_title: "INTERNATIONAL JUDGES PANEL",
    judges_subtitle: "Veteran IFBB Pro League officials bringing decades of adjudicating experience from premier global stages",

    // Drug Test
    dt_badge: "100% FAIR COMPETITION GUARANTEE",
    dt_title: "Rigorous Anti-Doping Standards",
    dt_desc: "The Natural Division at Global Classic Vietnam enforces strict anti-doping testing compliant with WADA (World Anti-Doping Agency) and NPC Worldwide:",
    dt_poly_title: "Polygraph Lie-Detector Examination",
    dt_poly_desc: "Mandatory for all athletes advancing to Natural Division medal contention.",
    dt_urine_title: "Urinalysis Laboratory Testing",
    dt_urine_desc: "Independent biological sample testing at ISO-certified international laboratories.",
    dt_ban_title: "36-Month Prohibited Substance Ban",
    dt_ban_desc: "Athletes must be 100% free from Anabolic Steroids, Growth Hormones, and banned stimulants for 3 years.",

    // FAQ
    faq_eyebrow: "FREQUENTLY ASKED QUESTIONS",
    faq_title: "ATHLETE FAQ",
    faq_subtitle: "Essential knowledge every competitor needs before taking the stage",
    faq_q1: "1. I am a first-time competitor. Can I enter Global Classic Vietnam?",
    faq_a1: "Absolutely! The championship features dedicated divisions for beginners (True Novice & Novice) before advancing to Open classes. It is the premier platform to gain valuable stage poise under international judging standards.",
    faq_q2: "2. What is the prestige and value of an IFBB Pro Card?",
    faq_a2: "The IFBB Pro Card is the most prestigious accreditation in world bodybuilding. Earning a Pro Card officially graduates an athlete from amateur ranks to the worldwide IFBB Professional League to vie for Mr. Olympia qualifications.",
    faq_q3: "3. What are the regulations regarding tanning and posing wear?",
    faq_a3: "Only IFBB-approved non-streaking competition tans are allowed (Official Pro Tan recommended). Men's Physique requires board shorts above the knee; Classic Physique wears black classic trunks; Bikini wears standard 2-piece suits.",
    faq_q4: "4. How do I submit my 60-second posing routine music?",
    faq_a4: "For Bodybuilding & Classic Physique competitors (60s routine), upon registration completion, you will receive a secure portal link to upload your high-quality MP3 track. Music submission closes 10 days before showtime.",
    faq_q5: "5. How can spectators and family purchase tickets?",
    faq_a5: "Spectator tickets (Standard, VIP, and Front-Row VVIP) are available directly on this official website or via hotline +84 93 883 39 79. All athletes who choose the Pro VIP package receive 1 complimentary VIP front-row pass.",

    // Highlights (Why choose)
    hl_eyebrow: "WHY CHOOSE NPC VIETNAM?",
    hl_title: "PREMIER GLOBAL STANDARDS",
    hl_subtitle: "Dedicated to building the strongest and most respected foundation for your bodybuilding career",
    hl_card1_title: "Official NPC Sanction",
    hl_card1_desc: "Directly sanctioned by NPC Worldwide and the international IFBB Professional League ecosystem.",
    hl_card2_title: "Acclaimed Judging Panel",
    hl_card2_desc: "Accredited international judges ensuring supreme integrity, impartiality, and transparency.",
    hl_card3_title: "Explosive Media Reach",
    hl_card3_desc: "Premier sports media production delivering high-resolution visuals to amplify athlete personal brands.",
    hl_card4_title: "Elite Fitness Network",
    hl_card4_desc: "A powerhouse community uniting top coaches, gym owners, sports nutrition brands, and passionate fitness enthusiasts.",

    // Sponsors
    sponsors_eyebrow: "STRATEGIC PARTNERS",
    sponsors_title: "POWERING THE PINNACLE OF VIETNAM BODYBUILDING",

    // Gallery
    gallery_eyebrow: "IMMORTAL MOMENTS",
    gallery_title: "PHOTO & MEDIA GALLERY",
    gallery_subtitle: "Stage lighting, sculpted muscles, and the triumphant euphoria of champions",

    // Register Form
    cta_eyebrow: "CONQUER THE PEAK OF GLORY",
    cta_title: "READY TO STEP ONTO THE STAGE?",
    cta_desc: "Do not let your gym sweat stay in the shadows. Step into the spotlight, assert your physique excellence before thousands, and carve your name into NPC Vietnam history.",
    form_fullname: "Full Name *",
    form_fullname_ph: "e.g. John Doe",
    form_phone: "Phone Number *",
    form_phone_ph: "e.g. +84 912 345 678",
    form_email: "Email Address *",
    form_email_ph: "example@domain.com",
    form_division: "Select Division *",
    form_div_default: "-- Select Your Division --",
    form_agree: "I agree to all competition bylaws, anti-doping regulations, and codes of conduct of NPC Worldwide.",
    btn_submit_form: "SUBMIT REGISTRATION",
    assure_secure: "Athlete Data Confidentiality",
    assure_support: "24/7 Competitor Support",
    assure_confirm: "Instant Email & SMS Confirmation",

    // Footer
    footer_bio: "Vietnam's premier bodybuilding championship, officially sanctioned by NPC Worldwide & IFBB Pro League.",
    footer_quick_links: "Quick Links",
    footer_rules_support: "Bylaws & Support",
    footer_office: "Organizing Committee",
    footer_address: "Rach Mieu Stadium, 01 Hoa Phuong, Ward 2, Phu Nhuan Dist, HCMC, Vietnam",
    footer_hotline: "Athlete Hotline: +84 93 883 39 79",
    footer_copyright: "© 2026 NPC Vietnam Championship. All rights reserved. Sanctioned by NPC Worldwide & IFBB Pro League."
  }
};

window.i18nData = i18nData;
