/**
 * NPC VIETNAM - NPC WORLDWIDE VIETNAM
 * Bilingual Translation Dictionary (Tiếng Việt & English)
 * Standard IFBB Pro League & NPC Worldwide Bodybuilding Terminology
 */

const i18nData = {
  vi: {
    // Header & Navigation
    nav_home: "Trang chủ",
    nav_about: "Giới thiệu",
    nav_procard: "Pro Cards",
    nav_divisions: "Hạng mục",
    nav_schedule: "Lịch trình",
    nav_packages: "Gói đấu",
    nav_judges: "Giám khảo",
    nav_gallery: "Thư viện",
    nav_faq: "FAQ",
    btn_register_nav: "Đăng ký thi đấu",

    // Hero Section
    hero_badge: "NPC REGIONAL & IFBB PRO QUALIFIER",
    hero_title_sub: "CONQUER THE STAGE",
    hero_desc: "Đấu trường thể hình đỉnh cao thuộc hệ thống NPC Worldwide & IFBB Pro League. Nơi hội tụ các chiến binh xuất sắc nhất tranh đoạt 8 chiếc thẻ IFBB PRO CARD vươn tầm thế giới.",
    btn_hero_register: "Đăng ký thi đấu ngay",
    btn_hero_trailer: "Trailer 4K Sân Khấu",
    hero_venue_pill: "EMPIRE FITNESS",
    stat_pro_cards: "IFBB PRO CARDS",
    stat_athletes: "Vận động viên",
    stat_stadium: "HCMC Stadium",
    scroll_down: "CUỘN XUỐNG",

    // Pro Cards Section
    procard_eyebrow: "ĐỈNH CAO DANH VỌNG",
    procard_title: "TRANH ĐOẠT 08 CHIẾC THẺ IFBB PRO CARD",
    procard_subtitle: "Chiếc vé thông hành quyền lực nhất thế giới thể hình, mở toang cánh cửa bước ra đấu trường Olympia danh giá tại Hoa Kỳ",
    procard_alloc_title: "Phân Bổ 8 Thẻ IFBB Pro Card Năm 2026",
    procard_alloc_desc: "Mỗi hạng mục thi đấu sẽ tìm ra các nhà vô địch Overall để trao trực tiếp thẻ Pro Card ngay trong đêm Gala Chung Kết:",
    procard_mens_physique: "02 Thẻ Pro Card (Open & Masters)",
    procard_classic: "02 Thẻ Pro Card (Open Division)",
    procard_bodybuilding: "01 Thẻ Pro Card (Overall Champion)",
    procard_bikini: "01 Thẻ Pro Card (Overall Champion)",
    procard_wellness: "01 Thẻ Pro Card (Overall Champion)",
    procard_figure: "01 Thẻ Pro Card (Overall Champion)",
    road_step1_title: "Gia Nhập NPC Worldwide",
    road_step1_desc: "Thi đấu giải Regional trong nước để tích lũy điểm & kinh nghiệm sân khấu.",
    road_step2_title: "Giành Overall Tại NPC WORLDWIDE",
    road_step2_desc: "Vượt qua các đối thủ sừng sỏ nhất để nhận thẻ IFBB Pro Card chính thức.",
    road_step3_title: "Bản Đồ IFBB Pro Thế Giới",
    road_step3_desc: "Tham gia các giải Pro Show toàn cầu tranh vé bước vào thánh đường Mr. Olympia.",

    // About Section
    about_eyebrow: "DI SẢN & TIÊU CHUẨN",
    about_title: "ĐẲNG CẤP THỂ HÌNH CHUYÊN NGHIỆP",
    about_natural_title: "Natural Division",
    about_natural_sub: "Chứng nhận thi đấu minh bạch & chuẩn mực",
    about_lead: "Bước ngoặt lịch sử của phong trào thể hình đỉnh cao tại Việt Nam",
    about_p1: "NPC (National Physique Committee) là tổ chức thể hình phong trào lớn nhất hành tinh, chiếc nôi sản sinh ra các huyền thoại Mr. Olympia và vận động viên chuyên nghiệp hàng đầu.",
    about_p2: "Tại Việt Nam, NPC WORLDWIDE Vietnam Championship được vận hành với chuẩn mực quốc tế khắt khe nhất: hệ thống âm thanh, ánh sáng chuyên biệt cho cơ bắp, hội đồng trọng tài quốc tế IFBB uy tín và khâu tổ chức đạt chứng chỉ toàn cầu.",
    feat_pro_title: "Lộ trình IFBB Pro Card",
    feat_pro_desc: "Cửa ngõ chính thức để vận động viên Việt Nam ghi danh tranh vé Pro Qualifier quốc tế.",
    feat_stage_title: "Sân khấu ánh sáng chuyên biệt",
    feat_stage_desc: "Setup ánh sáng mô phỏng 100% sân khấu Arnold Classic & Olympia nhằm tôn vinh từng thớ cơ.",
    stat_lbl_athletes: "Vận động viên tranh tài",
    stat_lbl_divisions: "Thi đấu chuyên nghiệp",
    stat_lbl_fans: "Khán giả & Người hâm mộ",
    stat_lbl_prizes: "Tổng giải thưởng & Quà tặng",
    stat_divisions_unit: "Hạng mục",
    stat_prizes_unit: "Triệu+",

    // Divisions
    div_eyebrow: "DANH MỤC THI ĐẤU",
    div_title: "HẠNG MỤC TRANH TÀI",
    div_subtitle: "Mỗi hạng mục mang một quy chuẩn thẩm mỹ, độ cắt nét và tỷ lệ hình thể riêng biệt",
    div_mp_tag: "Nam Vận Động Viên",
    div_mp_desc: "Tôn vinh hình thể hình chữ V (V-Taper), vai rộng, eo thon gọn, cơ bụng 6 múi sắc nét cùng phong thái tự tin và năng động.",
    div_mp_attire: "Trang phục: Quần Board Shorts",
    div_mp_criteria: "Tiêu chí: Tỷ lệ vai/eo, độ khô, thần thái",

    div_cp_tag: "Kỷ Nguyên Vàng",
    div_cp_desc: "Sự hồi sinh của vẻ đẹp thể hình cổ điển thời kỳ Arnold Schwarzenegger: cơ bắp dày khối, độ đối xứng hoàn mỹ và Vacuum Pose.",
    div_cp_attire: "Trang phục: Classic Trunks đen",
    div_cp_criteria: "Tiêu chí: Khối lượng cơ có kiểm soát theo chiều cao",

    div_bb_tag: "Đỉnh Cao Khối Lượng",
    div_bb_desc: "Hạng mục đỉnh cao nhất về độ dày khối cơ (mass), độ xé sợi (conditioning) và chi tiết cơ bắp vượt trội từ đầu đến chân.",
    div_bb_attire: "Trang phục: Posing Trunks",
    div_bb_criteria: "Tiêu chí: Khối lượng tối đa, độ cắt nét, gân guốc",

    div_bi_tag: "Nữ Vận Động Viên",
    div_bi_desc: "Tôn vinh đường cong đồng hồ cát nữ tính, cơ mông tròn đầy, độ săn chắc vừa vặn và phong cách trình diễn catwalk quyến rũ.",
    div_bi_attire: "Trang phục: 2-piece Bikini lấp lánh",
    div_bi_criteria: "Tiêu chí: Tỷ lệ hình thể, sự mềm mại, biểu cảm",

    div_wn_tag: "Sức Mạnh & Đường Cong",
    div_wn_desc: "Dành cho các nữ vận động viên có phần thân dưới (đùi, hông, mông) phát triển mạnh mẽ vượt trội nhưng phần thân trên vẫn giữ nét thon gọn.",
    div_wn_attire: "Trang phục: Wellness Suit chuyên dụng",
    div_wn_criteria: "Tiêu chí: Mật độ cơ mông - đùi dày khỏe",

    div_fg_tag: "Hình Khối Sắc Nét",
    div_fg_desc: "Tập trung vào độ đối xứng, độ nét của cơ lưng xô hình chữ V, vai tròn và độ tách sợi cơ bắp không quá đồ sộ như Physique.",
    div_fg_attire: "Trang phục: Figure Suit bắt chéo lưng",
    div_fg_criteria: "Tiêu chí: Độ cân xứng cơ bắp, đường nét săn chắc",
    div_fm_tag: "Hạng Mục Mới",
    div_fm_desc: "Hạng mục mới dành cho nữ: vóc dáng balanced, săn chắc và healthy — tôn vinh vẻ đẹp thể thao tự nhiên cùng thần thái thời trang sàn diễn.",
    div_fm_attire: "Trang phục: 2-piece Bikini & High Heels",
    div_fm_criteria: "Tiêu chí: Tỷ lệ cơ thể, tông da, phong thái trình diễn",
    div_wp_tag: "Sức Mạnh Nữ Tính",
    div_wp_desc: "Nấc thang chuyên môn cao hơn dành cho nữ: khối cơ phát triển vượt trội, độ xé sợi sâu, vây cơ rõ nét cùng khả năng trình diễn poses chuyên nghiệp.",
    div_wp_attire: "Trang phục: Physique Suit hai mảnh",
    div_wp_criteria: "Tiêu chí: Khối cơ, độ khô, đối xứng & poses",

    btn_register_div: "Đăng ký hạng này →",

    // Schedule & Countdown
    sched_eyebrow: "ĐẾM NGƯỢC THỜI GIAN",
    sched_title: "LỊCH TRÌNH GIẢI ĐẤU",
    sched_subtitle: "Chuẩn bị sẵn sàng cho ngày hội lớn nhất của thể hình Việt Nam",
    cd_status: "ĐẾM NGƯỢC THỜI GIAN KHỞI TRANH",
    cd_date_info: "2 - 4 THÁNG 10, 2026 • EMPIRE FITNESS CENTER, TP. HỒ CHÍ MINH",
    cd_days: "NGÀY",
    cd_hours: "GIỜ",
    cd_minutes: "PHÚT",
    cd_seconds: "GIÂY",
    sched_mc_title: "Muscle Contest Vietnam",
    sched_mc_d1_time: "23 Oct",
    sched_mc_d1_head: "13:00 - 17:00",
    sched_mc_d1_desc: "Athletes Weight-in & Check-in",
    sched_mc_d2_time: "24 Oct",
    sched_mc_d2_head: "09:00 - 19:00",
    sched_mc_d2_desc: "Judging & Pre-Judging",
    sched_gc_title: "Global Classic Vietnam",
    sched_gc_d1_time: "2 Oct",
    sched_gc_d1_head: "13:00 - 17:00",
    sched_gc_d1_desc: "Athletes Weight-in & Check-in",
    sched_gc_d2_time: "3 & 4 Oct",
    sched_gc_d2_head: "09:00 - 19:00",
    sched_gc_d2_desc: "Judging & Pre-Judging",

    // Packages & Services
    pkg_eyebrow: "QUYỀN LỢI & DỊCH VỤ CHUYÊN NGHIỆP",
    pkg_title: "GÓI THI ĐẤU & DỊCH VỤ HỖ TRỢ",
    pkg_subtitle: "Được thiết kế trọn gói từ A-Z giúp vận động viên tập trung 100% tinh thần để đạt phong độ đỉnh cao nhất",
    pkg_ribbon: "PHỔ BIẾN NHẤT",
    pkg_ribbon: "PRO SHOW",
    pkg1_badge: "3 & 4 THÁNG 10",
    currency_vnd: "VNĐ",
    pkg1_name: "GLOBAL CLASSIC VIETNAM NATURALS 2026",
    pkg1_show1: "3 Oct — Regional Show",
    pkg1_show1_p1: "+ Hạng mục đầu tiên: <strong>$120</strong>",
    pkg1_show1_p2: "+ Hạng mục thứ 2 trở đi: <strong>$60</strong>",
    pkg1_show2: "4 Oct — Pro Qualifier Show",
    pkg1_show2_p1: "+ Hạng mục đầu tiên: <strong>$240</strong>",
    pkg1_show2_p2: "+ Hạng mục thứ 2 trở đi: <strong>$180</strong>",
    btn_pkg1: "Đăng ký ngay",

    pkg2_badge: "24 THÁNG 10",
    pkg2_name: "MUSCLE CONTEST VIETNAM",
    pkg2_show1: "24 Oct — Regional & Pro Qualifier Show",
    pkg2_show1_p1: "+ Hạng mục đầu tiên: <strong>$220</strong>",
    pkg2_show1_p2: "+ Hạng mục thứ 2 trở đi: <strong>$210</strong>",
    pkg2_show2: "Pro Show",
    pkg2_show2_p1: "Men's Physique & Master Men's Physique",
    btn_pkg2: "Đăng ký ngay",

    service_tanning_title: "Dịch Vụ Phun Da Pro Tan",
    service_tanning_desc: "Thực hiện bởi chuyên gia chứng nhận quốc tế, giữ màu chuẩn sáng đèn sân khấu.",
    service_media_title: "Media & Video Posing 4K",
    service_media_desc: "Ống kính chuyên nghiệp ghi lại từng sợi cơ sắc nét và góc quay cinematic.",
    service_coach_title: "Thẻ Coach Hậu Trường",
    service_coach_desc: "Cho phép HLV đồng hành trong khu vực khởi động, bơm cơ và chuẩn bị dầu bóng.",

    // Judges
    judges_eyebrow: "CÔNG TÂM - MINH BẠCH - ĐẲNG CẤP",
    judges_title: "HỘI ĐỒNG GIÁM KHẢO QUỐC TẾ",
    judges_subtitle: "Đội ngũ trọng tài IFBB Pro League kỳ cựu với bề dày hàng thập kỷ chấm điểm tại các đấu trường danh giá bậc nhất thế giới",
    judge1_bio: "Phó Chủ tịch kiêm Trưởng ban trọng tài (Head Judge) quyền lực của NPC, NPC Worldwide và IFBB Professional League. Anh là gương mặt tiêu biểu của thế hệ lãnh đạo trẻ đầy năng lượng, mang đến luồng gió mới hiện đại, cởi mở và giàu tính chuyên môn cho làng thể hình đỉnh cao thế giới.",
    judge2_bio: "Một trong những tượng đài kỳ cựu và giàu ảnh hưởng bậc nhất của làng thể hình Hồng Kông, hiện giữ vai trò Tổng trọng tài trưởng (Chief Judge) của tổ chức thể hình danh tiếng Global Classic.",
    judge3_bio: "Một trong những gương mặt \"cầm cân nảy mực\" uy tín và giàu kinh nghiệm bậc nhất trong hệ thống giải đấu của NPC Worldwide và IFBB Pro League tại khu vực Đông Nam Á cũng như trên toàn Châu Á.",

    // Drug Test
    dt_badge: "BẢO ĐẢM TÍNH CÔNG BẰNG TUYỆT ĐỐI",
    dt_title: "Quy Chuẩn Kiểm Tra Doping Khắt Khe",
    dt_desc: "Hạng mục Natural Division tại NPC WORLDWIDE Vietnam áp dụng quy trình kiểm tra chất cấm theo tiêu chuẩn của WADA (World Anti-Doping Agency) và NPC Worldwide:",
    dt_poly_title: "Kiểm tra Polygraph (Máy nói dối)",
    dt_poly_desc: "Bắt buộc đối với toàn bộ thí sinh lọt vào Top tranh huy chương Natural.",
    dt_urine_title: "Xét nghiệm mẫu sinh học (Urinalysis Lab Test)",
    dt_urine_desc: "Phân tích mẫu nước tiểu độc lập tại phòng thí nghiệm đạt chuẩn ISO quốc tế.",
    dt_ban_title: "Thời gian cấm kỵ 36 tháng",
    dt_ban_desc: "VĐV không sử dụng bất kỳ chất kích thích đồng hóa (Anabolic Steroids), Hormones tăng trưởng trong 3 năm.",

    // FAQ
    faq_eyebrow: "GIẢI ĐÁP THẮC MẮC",
    faq_title: "CÂU HỎI THƯỜNG GẶP (FAQ)",
    faq_subtitle: "Tất cả những thông tin then chốt vận động viên cần nắm rõ trước ngày bước lên sàn đấu",
    faq_q1: "1. Tôi là vận động viên mới, tôi có thể tham gia NPC WORLDWIDE Vietnam không?",
    faq_a1: "Hoàn toàn được! Giải đấu có các bảng đấu dành cho người mới (True Novice & Novice) trước khi bước vào bảng Open. Đây là cơ hội tuyệt vời nhất để bạn cọ xát và tích lũy bản lĩnh sân khấu tiêu chuẩn quốc tế.",
    faq_q2: "2. Thẻ IFBB Pro Card có giá trị như thế nào?",
    faq_a2: "Thẻ IFBB Pro Card là chứng nhận đẳng cấp cao nhất dành cho VĐV thể hình chuyên nghiệp trên toàn thế giới. Khi sở hữu thẻ Pro Card, bạn chính thức rời khỏi phong trào nghiệp dư để tham gia các giải Pro League thế giới và săn vé đến Mr. Olympia.",
    faq_q3: "3. Quy định về màu da sơn (Tanning) và trang phục thi đấu?",
    faq_a3: "Chỉ chấp nhận các dòng màu da chuyên dụng không lem không dính được IFBB phê duyệt (ưu tiên dịch vụ Official Pro Tan của BTC). Quần Men's Physique phải là Board Shorts dài trên gối; Classic Physique mặc quần đùi đen Classic Trunks; Bikini mặc trang phục 2 mảnh tiêu chuẩn.",
    faq_q4: "4. Tôi cần gửi nhạc trình diễn Posing Routine bằng cách nào?",
    faq_a4: "Đối với hạng mục Bodybuilding & Classic Physique (bài diễn 60 giây), sau khi hoàn tất đăng ký, bạn sẽ nhận được liên kết tải nhạc cá nhân lên hệ thống (định dạng MP3 chất lượng cao). Hạn chót nộp nhạc là 10 ngày trước giải đấu.",
    faq_q5: "5. Khán giả và người thân có thể mua vé vào xem như thế nào?",
    faq_a5: "Vé khán giả (Standard, VIP và VVIP Front-Row) được mở bán trực tiếp tại website này hoặc hotline BTC 093 883 39 79. Mỗi VĐV đăng ký gói Pro VIP đã được tặng kèm 01 vé VIP hàng đầu.",

    // Highlights (Why choose)
    hl_eyebrow: "TẠI SAO CHỌN NPC VIETNAM?",
    hl_title: "GIẢI ĐẤU ĐẲNG CẤP HÀNG ĐẦU",
    hl_subtitle: "Cam kết kiến tạo nền tảng vững chắc nhất cho sự nghiệp thể hình của bạn",
    hl_card1_title: "Chuẩn Quốc Tế NPC",
    hl_card1_desc: "Giải đấu được ủy quyền chính thức, liên kết trực tiếp với hệ sinh thái NPC Worldwide và IFBB Professional League toàn cầu.",
    hl_card2_title: "Ban Giám Khảo Uy Tín",
    hl_card2_desc: "Đội ngũ giám khảo quốc tế có chứng chỉ chấm thi chuyên nghiệp, đảm bảo sự công tâm, minh bạch và chính xác trong từng kết quả.",
    hl_card3_title: "Truyền Thông Bùng Nổ",
    hl_card3_desc: "Đội ngũ nhiếp ảnh và quay phim sân khấu thể thao hàng đầu ghi lại từng khoảnh khắc đỉnh cao, hỗ trợ xây dựng thương hiệu cá nhân VĐV.",
    hl_card4_title: "Cộng Đồng Đẳng Cấp",
    hl_card4_desc: "Môi trường kết nối giữa hàng trăm huấn luyện viên, chủ phòng gym, nhà tài trợ thực phẩm bổ sung và những người đam mê thể hình chân chính.",

    // Sponsors
    sponsors_eyebrow: "ĐỐI TÁC CHIẾN LƯỢC",
    sponsors_title: "ĐỒNG HÀNH CÙNG ĐỈNH CAO THỂ HÌNH VIỆT NAM",

    // Gallery
    gallery_eyebrow: "KHOẢNH KHẮC BẤT TỬ",
    gallery_title: "THƯ VIỆN HÌNH ẢNH",
    gallery_subtitle: "Ánh đèn sân khấu, những thớ cơ cắt xẻ và cảm xúc thăng hoa của nhà vô địch",
    gallery_item1_title: "Sân Khấu Chính Chung Kết",
    gallery_item1_desc: "Khoảnh khắc tôn vinh nhà vô địch",
    gallery_item2_title: "Men's Physique Front Pose",
    gallery_item2_desc: "Tỷ lệ hình thể cân đối đỉnh cao",
    gallery_item3_title: "Classic Vacuum Pose",
    gallery_item3_desc: "Tinh hoa thẩm mỹ thể hình cổ điển",
    gallery_item4_title: "Vòng So Sánh Callout",
    gallery_item4_desc: "Cuộc chiến không khoan nhượng từng thớ cơ",
    gallery_item5_title: "Bodybuilding Conditioning",
    gallery_item5_desc: "Độ khô và gân guốc phi thường",
    gallery_item6_title: "Stage Presence",
    gallery_item6_desc: "Khí chất tự tin của đấu sĩ",
    gallery_item7_title: "Rear Lat Spread",
    gallery_item7_desc: "Độ rộng lưng và nét tách cơ chi tiết",
    gallery_item8_title: "Focus & Discipline",
    gallery_item8_desc: "Thành quả của hàng ngàn giờ tập luyện",

    // Video Modal
    video_caption_desc: "Khoảnh khắc rực lửa trên sàn đấu thể hình chuyên nghiệp quốc tế",
    video_fallback: "Trình duyệt của bạn không hỗ trợ phát video HTML5.",

    // Register Form
    cta_eyebrow: "CHINH PHỤC ĐỈNH CAO VINH QUANG",
    cta_title: "SẴN SÀNG BƯỚC LÊN SÂN KHẤU?",
    cta_desc: "Đừng để những giọt mồ hôi trong phòng tập nằm lại trong bóng tối. Hãy bước ra ánh sáng, khẳng định sự vượt trội của bản thân trước hàng ngàn khán giả và ghi danh vào lịch sử NPC Vietnam.",
    svc_heading: "Dịch Vụ Muscle Contest Việt Nam 2026 Đã Mở Đăng Ký.",
    svc_booking: "Đặt lịch ngay hôm nay:",
    svc_makeup: "Make Up & Hair (Trang điểm & Tóc)",
    svc_tanning: "Tanning (Phun da)",
    svc_photo_basic: "Photo Basic (Ảnh cơ bản)",
    svc_photo_premium: "Photo Premium (Ảnh cao cấp)",
    svc_video_basic: "Video Basic (Video cơ bản)",
    svc_video_premium: "Video Premium (Video cao cấp)",
    svc_payment_how: "Hướng dẫn thanh toán:",
    svc_transfer: "Vui lòng chuyển khoản số tiền tương ứng. Ví dụ: nếu bạn muốn thanh toán dịch vụ Tanning (Phun da), hãy chuyển 90.00 USD vào tài khoản PayPal qua mã QR trong hình, hoặc đến tài khoản PayPal sau:",
    svc_paypal_account: "Tài khoản PayPal:",
    svc_paypal_email: "Email:",
    svc_details: "Điền nội dung chuyển khoản như sau:",
    svc_details_fmt: "Họ tên đầy đủ - Dịch vụ đã đăng ký",
    svc_screenshot: "Sau đó, chụp ảnh màn hình giao dịch và gửi qua Instagram đến @MuscleContestVietNam hoặc qua WhatsApp đến số +8493 8833 979 - Mr. Henry Ho.",
    svc_offline: "Bạn cũng có thể đăng ký trực tiếp tại văn phòng NPC Việt Nam.",
    form_fullname: "Họ và tên *",
    form_fullname_ph: "Ví dụ: Nguyễn Văn A",
    form_phone: "Số điện thoại *",
    form_phone_ph: "Ví dụ: 0912 345 678",
    form_email: "Địa chỉ Email *",
    form_email_ph: "example@domain.com",
    form_division: "Hạng mục đăng ký *",
    form_div_default: "-- Chọn hạng mục thi đấu --",
    form_agree: "Tôi đồng ý với các điều lệ, quy chuẩn kiểm tra doping và cam kết kỷ luật của NPC Worldwide.",
    btn_submit_form: "GỬI ĐĂNG KÝ THI ĐẤU",
    assure_secure: "Bảo mật thông tin VĐV",
    assure_support: "Hỗ trợ kỹ thuật 24/7",
    assure_confirm: "Xác nhận qua email & SMS ngay",

    // Footer
    footer_bio: "Sân chơi thể hình quy mô và chuẩn mực hàng đầu tại Việt Nam, trực thuộc hệ thống thi đấu quốc tế NPC Worldwide và IFBB Pro League.",
    footer_quick_links: "Liên Kết Nhanh",
    footer_rules_support: "Quy Chuẩn & Hỗ Trợ",
    footer_link_rules: "Luật chấm điểm IFBB",
    footer_link_doping: "Quy chuẩn Doping Test",
    footer_link_tanning: "Dịch vụ Tanning & Makeup",
    footer_link_benefits: "Quyền lợi VĐV Vô Địch",
    footer_link_privacy: "Chính sách bảo mật",
    footer_office: "Văn Phòng Ban Tổ Chức",
    footer_address: "Empire Fitness Center, 363 Phạm Hùng, Bình Hưng, TP. Hồ Chí Minh",
    footer_hotline: "Hotline: +8493 8833 979",
    footer_copyright: "© 2026 NPC Vietnam Championship. Bảo lưu mọi quyền. Liên kết chính thức cùng NPC Worldwide & IFBB Pro League."
  },

  en: {
    // Header & Navigation
    nav_home: "Home",
    nav_about: "About",
    nav_procard: "Pro Cards",
    nav_divisions: "Divisions",
    nav_schedule: "Schedule",
    nav_packages: "Packages",
    nav_judges: "Judges",
    nav_gallery: "Gallery",
    nav_faq: "FAQ",
    btn_register_nav: "Register Now",

    // Hero Section
    hero_badge: "NPC REGIONAL & IFBB PRO QUALIFIER",
    hero_title_sub: "CONQUER THE STAGE",
    hero_desc: "The pinnacle bodybuilding championship sanctioned by NPC Worldwide & IFBB Pro League. Where elite warriors assemble to contest for 8 coveted IFBB PRO CARDS to reach the global stage.",
    btn_hero_register: "Register to Compete",
    btn_hero_trailer: "Official 4K Trailer",
    hero_venue_pill: "EMPIRE FITNESS",
    stat_pro_cards: "IFBB PRO CARDS",
    stat_athletes: "Athletes",
    stat_stadium: "HCMC Stadium",
    scroll_down: "SCROLL DOWN",

    // Pro Cards Section
    procard_eyebrow: "PINNACLE OF GLORY",
    procard_title: "CONTEST FOR 08 IFBB PRO CARDS",
    procard_subtitle: "The most prestigious passport in the bodybuilding world, unlocking the gateway to the legendary Mr. Olympia stage in the USA",
    procard_alloc_title: "8 IFBB Pro Cards Allocation for 2026",
    procard_alloc_desc: "Each competitive division will determine Overall Champions awarded official Pro Cards directly on Finals Gala Night:",
    procard_mens_physique: "02 Pro Cards (Open & Masters)",
    procard_classic: "02 Pro Cards (Open Division)",
    procard_bodybuilding: "01 Pro Card (Overall Champion)",
    procard_bikini: "01 Pro Card (Overall Champion)",
    procard_wellness: "01 Pro Card (Overall Champion)",
    procard_figure: "01 Pro Card (Overall Champion)",
    road_step1_title: "Join NPC Worldwide",
    road_step1_desc: "Compete in domestic Regional contests to accumulate points & stage experience.",
    road_step2_title: "Win Overall at NPC WORLDWIDE",
    road_step2_desc: "Outshine the best competitors to claim your official IFBB Pro Card.",
    road_step3_title: "The Global IFBB Pro Circuit",
    road_step3_desc: "Compete in worldwide Pro Shows to earn qualification directly to Mr. Olympia.",

    // About Section
    about_eyebrow: "LEGACY & STANDARDS",
    about_title: "PREMIER PROFESSIONAL BODYBUILDING",
    about_natural_title: "Natural Division",
    about_natural_sub: "Certified transparent & drug-tested standards",
    about_lead: "A historic milestone for elite bodybuilding in Vietnam",
    about_p1: "The NPC (National Physique Committee) is the largest amateur physique organization on earth, the birthplace of Mr. Olympia legends and world-renowned professional athletes.",
    about_p2: "In Vietnam, the NPC WORLDWIDE Vietnam Championship is executed under rigorous international standards: custom stage lighting tailored for muscle definition, accredited IFBB international judges, and world-class event production.",
    feat_pro_title: "Direct IFBB Pro Pathway",
    feat_pro_desc: "Official gateway for Vietnamese and international athletes to qualify for world Pro Qualifiers.",
    feat_stage_title: "Custom Pro Stage Lighting",
    feat_stage_desc: "100% replicated Arnold Classic & Olympia lighting rigs engineered to accentuate every muscle fiber.",
    stat_lbl_athletes: "Competing Athletes",
    stat_lbl_divisions: "Professional Divisions",
    stat_lbl_fans: "Spectators & Fans",
    stat_lbl_prizes: "Total Awards & Prize Pool",
    stat_divisions_unit: "Divisions",
    stat_prizes_unit: "Million+",

    // Divisions
    div_eyebrow: "COMPETITION CATEGORIES",
    div_title: "OFFICIAL DIVISIONS",
    div_subtitle: "Each division represents a distinct aesthetic standard, conditioning depth, and physique proportion",
    div_mp_tag: "Men's Category",
    div_mp_desc: "Emphasizes the signature V-Taper, wide shoulders, tapered waist, sculpted six-pack abs, and an energetic, confident stage persona.",
    div_mp_attire: "Attire: Board Shorts",
    div_mp_criteria: "Criteria: V-Taper, Conditioning, Stage Presence",

    div_cp_tag: "Golden Era",
    div_cp_desc: "The resurrection of classic bodybuilding aesthetics from the Arnold Schwarzenegger era: dense muscle bellies, flawless symmetry, and the iconic Vacuum Pose.",
    div_cp_attire: "Attire: Solid Black Classic Trunks",
    div_cp_criteria: "Criteria: Height-to-Weight Ratio & Symmetry",

    div_bb_tag: "Maximum Mass",
    div_bb_desc: "The pinnacle of muscle density, deep striations, exceptional conditioning, and head-to-toe muscular detail.",
    div_bb_attire: "Attire: Posing Trunks",
    div_bb_criteria: "Criteria: Maximum Mass, Striations & Vascularity",

    div_bi_tag: "Women's Category",
    div_bi_desc: "Showcases feminine hourglass curves, full glutes, moderate tone, and an elegant, glamorous runway presentation.",
    div_bi_attire: "Attire: Two-Piece Stage Bikini",
    div_bi_criteria: "Criteria: Balance, Poise & Glamour Presentation",

    div_wn_tag: "Power & Curves",
    div_wn_desc: "Dedicated to female athletes with heavily developed lower bodies (quads, glutes, hamstrings) while maintaining a balanced upper physique.",
    div_wn_attire: "Attire: Official Wellness Suit",
    div_wn_criteria: "Criteria: Dense Hip, Glute & Thigh Mass",

    div_fg_tag: "Athletic Symmetry",
    div_fg_desc: "Focuses on muscular symmetry, V-shaped wide lats, rounded delts, and clear separation without extreme mass.",
    div_fg_attire: "Attire: Criss-Cross Figure Suit",
    div_fg_criteria: "Criteria: X-Frame, Wide Lats & Firm Tone",
    div_fm_tag: "New Division",
    div_fm_desc: "A brand-new women's division celebrating balanced, toned and healthy physiques — honoring natural athletic beauty with runway-ready stage presence.",
    div_fm_attire: "Attire: Two-Piece Bikini & High Heels",
    div_fm_criteria: "Criteria: Body Proportions, Skin Tone & Presentation",
    div_wp_tag: "Feminine Power",
    div_wp_desc: "The next competitive level for women: superior muscle development, deep conditioning, clear separation, and professional pose execution.",
    div_wp_attire: "Attire: Two-Piece Physique Suit",
    div_wp_criteria: "Criteria: Muscle Mass, Conditioning, Symmetry & Posing",

    btn_register_div: "Register this division →",

    // Schedule & Countdown
    sched_eyebrow: "COUNTDOWN TO SHOWTIME",
    sched_title: "EVENT SCHEDULE",
    sched_subtitle: "Gear up for Vietnam's biggest fitness & bodybuilding festival",
    cd_status: "COUNTDOWN TO SHOWTIME",
    cd_date_info: "OCTOBER 2 - 4, 2026 • EMPIRE FITNESS CENTER, HO CHI MINH CITY",
    cd_days: "DAYS",
    cd_hours: "HOURS",
    cd_minutes: "MINS",
    cd_seconds: "SECS",
    sched_mc_title: "Muscle Contest Vietnam",
    sched_mc_d1_time: "Oct 23",
    sched_mc_d1_head: "1:00 PM - 5:00 PM",
    sched_mc_d1_desc: "Athletes Weight-in & Check-in",
    sched_mc_d2_time: "Oct 24",
    sched_mc_d2_head: "9:00 AM - 7:00 PM",
    sched_mc_d2_desc: "Judging & Pre-Judging",
    sched_gc_title: "Global Classic Vietnam",
    sched_gc_d1_time: "Oct 2",
    sched_gc_d1_head: "1:00 PM - 5:00 PM",
    sched_gc_d1_desc: "Athletes Weight-in & Check-in",
    sched_gc_d2_time: "Oct 3 & 4",
    sched_gc_d2_head: "9:00 AM - 7:00 PM",
    sched_gc_d2_desc: "Judging & Pre-Judging",

    // Packages & Services
    pkg_eyebrow: "ATHLETE PRIVILEGES & SERVICES",
    pkg_title: "COMPETITION PACKAGES & SUPPORT",
    pkg_subtitle: "End-to-end services crafted so athletes can focus 100% on peak physical and mental condition",
    pkg_ribbon: "MOST POPULAR",
    pkg_ribbon: "PRO SHOW",
    pkg1_badge: "OCT 3 & 4",
    currency_vnd: "VND",
    pkg1_name: "GLOBAL CLASSIC VIETNAM NATURALS 2026",
    pkg1_show1: "Oct 3 — Regional Show",
    pkg1_show1_p1: "+ First division: <strong>$120</strong>",
    pkg1_show1_p2: "+ Each additional division: <strong>$60</strong>",
    pkg1_show2: "Oct 4 — Pro Qualifier Show",
    pkg1_show2_p1: "+ First division: <strong>$240</strong>",
    pkg1_show2_p2: "+ Each additional division: <strong>$180</strong>",
    btn_pkg1: "Register Now",

    pkg2_badge: "OCT 24",
    pkg2_name: "MUSCLE CONTEST VIETNAM",
    pkg2_show1: "Oct 24 — Regional & Pro Qualifier Show",
    pkg2_show1_p1: "+ First division: <strong>$220</strong>",
    pkg2_show1_p2: "+ Each additional division: <strong>$210</strong>",
    pkg2_show2: "Pro Show",
    pkg2_show2_p1: "Men's Physique & Master Men's Physique",
    btn_pkg2: "Register Now",

    service_tanning_title: "Official Pro Tan Service",
    service_tanning_desc: "Applied by certified international tanning technicians, calibrated for optimal stage lighting.",
    service_media_title: "Media & 4K Posing Video",
    service_media_desc: "High-end sports photography & cinematic 4K video capturing every muscle striation.",
    service_coach_title: "Backstage Coach Pass",
    service_coach_desc: "Permits personal coaches access to pump-up rooms, glaze applications, and backstage staging.",

    // Judges
    judges_eyebrow: "IMPARTIAL - TRANSPARENT - ELITE",
    judges_title: "INTERNATIONAL JUDGES PANEL",
    judges_subtitle: "Veteran IFBB Pro League officials bringing decades of adjudicating experience from premier global stages",
    judge1_bio: "Vice President and powerful Head Judge of NPC, NPC Worldwide and IFBB Professional League. A standout figure of a young, energetic leadership generation bringing a modern, open and highly professional new wave to elite world bodybuilding.",
    judge2_bio: "One of the most veteran and influential icons of the Hong Kong bodybuilding scene, currently serving as Chief Judge of the prestigious Global Classic organization.",
    judge3_bio: "One of the most reputable and experienced arbiters in the NPC Worldwide and IFBB Pro League competition system across Southeast Asia and the whole of Asia.",

    // Drug Test
    dt_badge: "100% FAIR COMPETITION GUARANTEE",
    dt_title: "Rigorous Anti-Doping Standards",
    dt_desc: "The Natural Division at NPC WORLDWIDE Vietnam enforces strict anti-doping testing compliant with WADA (World Anti-Doping Agency) and NPC Worldwide:",
    dt_poly_title: "Polygraph Lie-Detector Examination",
    dt_poly_desc: "Mandatory for all athletes advancing to Natural Division medal contention.",
    dt_urine_title: "Urinalysis Laboratory Testing",
    dt_urine_desc: "Independent biological sample testing at ISO-certified international laboratories.",
    dt_ban_title: "36-Month Prohibited Substance Ban",
    dt_ban_desc: "Athletes must be 100% free from Anabolic Steroids, Growth Hormones, and banned stimulants for 3 years.",

    // FAQ
    faq_eyebrow: "FREQUENTLY ASKED QUESTIONS",
    faq_title: "ATHLETE FAQ",
    faq_subtitle: "Essential knowledge every competitor needs before taking the stage",
    faq_q1: "1. I am a first-time competitor. Can I enter NPC WORLDWIDE Vietnam?",
    faq_a1: "Absolutely! The championship features dedicated divisions for beginners (True Novice & Novice) before advancing to Open classes. It is the premier platform to gain valuable stage poise under international judging standards.",
    faq_q2: "2. What is the prestige and value of an IFBB Pro Card?",
    faq_a2: "The IFBB Pro Card is the most prestigious accreditation in world bodybuilding. Earning a Pro Card officially graduates an athlete from amateur ranks to the worldwide IFBB Professional League to vie for Mr. Olympia qualifications.",
    faq_q3: "3. What are the regulations regarding tanning and posing wear?",
    faq_a3: "Only IFBB-approved non-streaking competition tans are allowed (Official Pro Tan recommended). Men's Physique requires board shorts above the knee; Classic Physique wears black classic trunks; Bikini wears standard 2-piece suits.",
    faq_q4: "4. How do I submit my 60-second posing routine music?",
    faq_a4: "For Bodybuilding & Classic Physique competitors (60s routine), upon registration completion, you will receive a secure portal link to upload your high-quality MP3 track. Music submission closes 10 days before showtime.",
    faq_q5: "5. How can spectators and family purchase tickets?",
    faq_a5: "Spectator tickets (Standard, VIP, and Front-Row VVIP) are available directly on this official website or via hotline +84 93 883 39 79. All athletes who choose the Pro VIP package receive 1 complimentary VIP front-row pass.",

    // Highlights (Why choose)
    hl_eyebrow: "WHY CHOOSE NPC VIETNAM?",
    hl_title: "PREMIER GLOBAL STANDARDS",
    hl_subtitle: "Dedicated to building the strongest and most respected foundation for your bodybuilding career",
    hl_card1_title: "Official NPC Sanction",
    hl_card1_desc: "Directly sanctioned by NPC Worldwide and the international IFBB Professional League ecosystem.",
    hl_card2_title: "Acclaimed Judging Panel",
    hl_card2_desc: "Accredited international judges ensuring supreme integrity, impartiality, and transparency.",
    hl_card3_title: "Explosive Media Reach",
    hl_card3_desc: "Premier sports media production delivering high-resolution visuals to amplify athlete personal brands.",
    hl_card4_title: "Elite Fitness Network",
    hl_card4_desc: "A powerhouse community uniting top coaches, gym owners, sports nutrition brands, and passionate fitness enthusiasts.",

    // Sponsors
    sponsors_eyebrow: "STRATEGIC PARTNERS",
    sponsors_title: "POWERING THE PINNACLE OF VIETNAM BODYBUILDING",

    // Gallery
    gallery_eyebrow: "IMMORTAL MOMENTS",
    gallery_title: "PHOTO & MEDIA GALLERY",
    gallery_subtitle: "Stage lighting, sculpted muscles, and the triumphant euphoria of champions",
    gallery_item1_title: "Finals Main Stage",
    gallery_item1_desc: "Crowning the ultimate champions",
    gallery_item2_title: "Men's Physique Front Pose",
    gallery_item2_desc: "Pinnacle of aesthetic proportion",
    gallery_item3_title: "Classic Vacuum Pose",
    gallery_item3_desc: "Essence of golden era aesthetics",
    gallery_item4_title: "Stage Callout Comparisons",
    gallery_item4_desc: "Fierce head-to-head battle of muscles",
    gallery_item5_title: "Bodybuilding Conditioning",
    gallery_item5_desc: "Deep striations & raw vascularity",
    gallery_item6_title: "Stage Presence",
    gallery_item6_desc: "Radiant confidence and poise",
    gallery_item7_title: "Rear Lat Spread",
    gallery_item7_desc: "Impressive V-taper and back separation",
    gallery_item8_title: "Focus & Discipline",
    gallery_item8_desc: "Reward of thousands of grinding hours",

    // Video Modal
    video_caption_desc: "Igniting the fire on the international professional bodybuilding stage",
    video_fallback: "Your browser does not support HTML5 video playback.",

    // Register Form
    cta_eyebrow: "CONQUER THE PEAK OF GLORY",
    cta_title: "READY TO STEP ONTO THE STAGE?",
    cta_desc: "Do not let your gym sweat stay in the shadows. Step into the spotlight, assert your physique excellence before thousands, and carve your name into NPC Vietnam history.",
    svc_heading: "Services For Muscle Contest VietNam 2026 Now Open.",
    svc_booking: "Booking Today:",
    svc_makeup: "Make Up & Hair",
    svc_tanning: "Tanning",
    svc_photo_basic: "Photo Basic",
    svc_photo_premium: "Photo Premium",
    svc_video_basic: "Video Basic",
    svc_video_premium: "Video Premium",
    svc_payment_how: "How to make a payment:",
    svc_transfer: "Please transfer the corresponding amount. For example, if you want to pay for the Tanning service, transfer $90.00 USD to the PayPal Account using the QR code in the image, or to the following PayPal Account:",
    svc_paypal_account: "PayPal Account:",
    svc_paypal_email: "Email:",
    svc_details: "Include the following in the transaction details:",
    svc_details_fmt: "Full Name - Service Registered",
    svc_screenshot: "After that, take a screenshot of the transaction and send it via Instagram to @MuscleContestVietNam or via WhatsApp to +8493 8833 979 - Mr. Henry Ho.",
    svc_offline: "You can also register offline at the NPC Vietnam.",
    form_fullname: "Full Name *",
    form_fullname_ph: "e.g. John Doe",
    form_phone: "Phone Number *",
    form_phone_ph: "e.g. +84 912 345 678",
    form_email: "Email Address *",
    form_email_ph: "example@domain.com",
    form_division: "Select Division *",
    form_div_default: "-- Select Your Division --",
    form_agree: "I agree to all competition bylaws, anti-doping regulations, and codes of conduct of NPC Worldwide.",
    btn_submit_form: "SUBMIT REGISTRATION",
    assure_secure: "Athlete Data Confidentiality",
    assure_support: "24/7 Competitor Support",
    assure_confirm: "Instant Email & SMS Confirmation",

    // Footer
    footer_bio: "Vietnam's premier bodybuilding championship, officially sanctioned by NPC Worldwide & IFBB Pro League.",
    footer_quick_links: "Quick Links",
    footer_rules_support: "Bylaws & Support",
    footer_link_rules: "IFBB Judging Criteria",
    footer_link_doping: "Anti-Doping Regulations",
    footer_link_tanning: "Tanning & Stage Services",
    footer_link_benefits: "Champion Privileges",
    footer_link_privacy: "Privacy Policy",
    footer_office: "Organizing Committee",
    footer_address: "Empire Fitness Center, 363 Pham Hung, Binh Hung, HCMC, Vietnam",
    footer_hotline: "Hotline: +8493 8833 979",
    footer_copyright: "© 2026 NPC Vietnam Championship. All rights reserved. Sanctioned by NPC Worldwide & IFBB Pro League."
  }
};

window.i18nData = i18nData;
